name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno and Vite
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.25.4

      - name: Build app
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "lambtron-deno-vite-project"
          entrypoint: https://deno.land/std@0.157.0/http/file_server.ts
          root: dist
